### ISSUE TITLE
File not found upon project generation

### ISSUE THREAD

**Issue by whiver** [gautamsi/generator-keystone-ts#2]
Under Linux, it seems that there is a case issue, since I'm getting this error at the beginning of project generation:

```
/usr/lib/node_modules/generator-keystone-ts/node_modules/yeoman-generator/lib/actions/actions.js:191
    throw new Error('Unable to read "' + filepath + '" file (Error code: ' + e.code + ').');
    ^

Error: Unable to read "/usr/lib/node_modules/generator-keystone-ts/app/templates/_README.MD" file (Error code: ENOENT).
    at KeystoneGenerator.read (/usr/lib/node_modules/generator-keystone-ts/node_modules/yeoman-generator/lib/actions/actions.js:191:11)
    at KeystoneGenerator.template (/usr/lib/node_modules/generator-keystone-ts/node_modules/yeoman-generator/lib/actions/actions.js:286:19)
    at KeystoneGenerator.project (/usr/lib/node_modules/generator-keystone-ts/app/index.js:317:7)
    at /usr/lib/node_modules/generator-keystone-ts/node_modules/yeoman-generator/lib/base.js:395:14
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

```

**Comment by whiver** [comment]
It works when I replace in `index.js` this line:

	this.template('_README.MD', 'README.md');

with:

	this.template('_README.md');
